### ISSUE TITLE
Question: Do I need you plugin in yorder to receive push notification from azure?

### ISSUE THREAD

**Issue by philippsander** [PeterStaev/nativescript-azure-mobile-apps#15]

**Comment by Habeeb-mohamed** [comment]
This plugin make the registration process easier. It uses azure push notification framework by Microsoft for iOS. If you use this no need to write any thing on back-end. Configure on azure Dashboard (push notification hub) and
Just have to write the code as mentioned in README.md

**Comment by PeterStaev** [comment]
Hey @philippsander , I think the answer above from @Habeeb-mohamed correctly answers your question.
