### ISSUE TITLE
Question: Firebase ID in my settings?

### ISSUE THREAD

**Issue by philippsander** [PeterStaev/nativescript-azure-mobile-apps#18]
Why should i use this plugin, when i still need a firebase ID?

**Comment by PeterStaev** [comment]
Hey @philippsander , this plugin only unifies access for both Android and iOS so you can send push notifications to both platforms. Similarly how you need an Apple push certificate installed in Azure for iOS notification, you need firebase ID and App ID registered with Google and entered on the Azure portal.

**Comment by philippsander** [comment]
> you need firebase ID and App ID registered with Google and entered on the Azure portal.

do you mean the azure portal needs firebase?!

**Comment by PeterStaev** [comment]
Of course it needs it. Like I said Azure just wraps up iOS and Android push under a same API calls so you can call one API and send to both platforms. In the back it still uses GCM (or now FCM) to send to Android devices and APN to send to iOS devices. Take a look at https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-android-push-notification-google-gcm-get-started

**Comment by philippsander** [comment]
but GCM is not firebase...

**Comment by PeterStaev** [comment]
Actually you are wrong, FCM superseded GCM. Take a look at https://developers.google.com/cloud-messaging/

**Comment by philippsander** [comment]
sorry this is all new for me. 

> Firebase Cloud Messaging (FCM) is the new version of GCM.

I understood this as: FCM is something different than GCM. it's the new version. you can still use GCM if you want.

**Comment by philippsander** [comment]
my main question here is: can I use your plugin with GCM?

**Comment by PeterStaev** [comment]
I haven't tried but I guess it should work.
