### ISSUE TITLE
TNS3 Support

### ISSUE THREAD

**Issue by shivapersad** [PeterStaev/nativescript-azure-mobile-apps#21]
Good day,

Is this plugin compatible with TNS 3? Thanks.

**Comment by PeterStaev** [comment]
@shivapersad haven't tested personally but it should be compatible as it does not use any UI specific classes that were changed in TNS 3.

**Comment by shivapersad** [comment]
@PeterStaev thanks for the reply. I'll test it in my app and let you know if it's still working properly.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you experience problems with TNS 3+ please submit separate issues describing the specific problem.
