### ISSUE TITLE
registration error

### ISSUE THREAD

**Issue by gregersen79** [PeterStaev/nativescript-azure-mobile-apps#23]
When calling the register() function, I get the following error on Android:

>  java.io.IOException: stream was reset: PROTOCOL_ERROR

and sometimes the error: 

> java.io.IOException: shutdown

and the following error on iOS:

> Error: <Error><Code>401</Code><Detail>Missing authorization token.TrackingId:07f86ede-c095-4d7d-a0a9-8293966c3261_G42,TimeStamp:8/30/2017 7:26:26 AM</Detail></Error>

Any ideas why, what I'm missing?

**Comment by PeterStaev** [comment]
Hey @gregersen79 , sadly I have not seen those errors so cant really help you. Make sure you have added your GCM API Key/Apple Push cert to your Azure portal notification hub.

**Comment by gregersen79** [comment]
Hey @PeterStaev, thank you for your answer, thats okay. I can't seem to find a solution for this error, so we decided to manage the registration server-side, and this works fine.
