### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jeremywhiteley** [PeterStaev/nativescript-azure-mobile-apps#25]
Will this work with the new Azure B2C MSAL with Azure App Service?   What about with Angular / Nativescript with a cross platform?    Angular 5 for web, and Nativescript / Angular with Mobile?

**Comment by PeterStaev** [comment]
Hey @Jeremywhiteley , this plugin is specifically designed to the mobile platform and uses the android/ios binaries to do communication with Azure. If you want to have cross web/native you will have to wrap it together with whatever API azure has for the web platform and then either call the methods of this plugin if it runs on the mobile platform or call the web platform APIs. 

As for MSAL - i'm not very familiar with it, but from what I see this is for web apps and not for mobile, so I think the plugin will not work.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
