### ISSUE TITLE
Angular import

### ISSUE THREAD

**Issue by Cambia86** [PeterStaev/nativescript-azure-mobile-apps#26]
Hi @PeterStaev, sorry if can be a stupid question but i'm new on nativescript...
I choose angular 5 with nativescript and  can't import your plugin, it's says
Module nativescript-azure-mobile-apps/client not found

Can you help me?
Thanks

**Comment by PeterStaev** [comment]
Hey @Cambia86 , a new version was just released that should simplify the import and fix your problem. If it doesn't try adding this line to your file
```ts
/// <reference path="../node_modules/nativescript-azure-mobile-apps/azure-mobile-apps.d.ts" />
```

**Comment by Cambia86** [comment]
Hi @PeterStaev,
just try this way, i really don't understand

![cattura](https://user-images.githubusercontent.com/17907232/38082058-dd1c60c0-3345-11e8-8a23-f2cb07424030.PNG)

**Comment by PeterStaev** [comment]
I've just tried the new version in a an angular project and it works w/o the reference. Please update the plugin and then restart VS Code (as it sometimes give false positive as it does not refresh definitions for the installed packages.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
