### ISSUE TITLE
Azure B2C Authentication

### ISSUE THREAD

**Issue by johny8228** [PeterStaev/nativescript-azure-mobile-apps#27]
Hi,

does this plugin works with Azure B2C authentication as well?

Thanks,
Johnny

**Comment by PeterStaev** [comment]
Hey @johny8228 , I haven't personally tried it but from what I see the plugin should support Server managed B2C authentication as explained here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app#server-managed-authentication

You just have to use the Azure Active Directory provider as shown in this snippet: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app#server-managed-authentication

Also make sure you make all the required changes and settings in the Azure Portal as explained in the article. 

Feel free to try it out and report back if it works or not 😉

**Comment by johny8228** [comment]
@PeterStaev thank you for your answer, much appreciated.So the Client-managed authentication it is not supported by this plugin, since I was looking more into this, through Server based authentication I basicly wrap the B2C authentication in an webservice.

**Comment by PeterStaev** [comment]
That is correct.

**Comment by PeterStaev** [comment]
No further response so closing this one for now.
