### ISSUE TITLE
TypeError: MobileServiceClient is not a constructor

### ISSUE THREAD

**Issue by axprin** [PeterStaev/nativescript-azure-mobile-apps#29]
I'm trying to use this plugin to interface with an Azure db. As instructed in the documentation, I have configured the `AndroidManifest.xml` and `app.gradle` files correctly. My usage is as follows:

```javascript
var MobileServiceClient = require("nativescript-azure-mobile-apps/client");

try {
    var client = new MobileServiceClient("****.database.windows.net");
} catch (error) {
    console.log("error with Azure stuff: ", error);
}
```

And I get the following in the console:
`JS: error with Azure stuff:  TypeError: MobileServiceClient is not a constructor`

**Comment by PeterStaev** [comment]
Hey @axprin , you are not importing the plugin correctly. It is best you use TypeScript or if you want to use JS to look at the transpiled files after you build the demo app so you can see how things are imported. In you case the import statement should be something like:
```js
var MobileServiceClient = require("nativescript-azure-mobile-apps/client").MobileServiceClient;
```

Also I do not think the plugin will work if you connect it directly to Azure DB URL. As the name of the plugin says, it is meant to be used with the Azure Mobile Apps.

**Comment by axprin** [comment]
@PeterStaev Thank you!
