### ISSUE TITLE
User can't click and close modal Login window on Android

### ISSUE THREAD

**Issue by dehlers1000** [PeterStaev/nativescript-azure-mobile-apps#37]
I am able to successfully use Azure AD B2C with Azure Mobile Services in Android using the nativescript-azure-mobile-apps plugin. However, there is no close option on the WebView window. It would be beneficial to have a close X icon on the top left or right of the screen. At first, I was stuck clicking around trying to close the modal window with no luck. Then I clicked the back button on the phone to return to the main page. The plugin works great and this is the only show stopper for me implementing this in a production environment. It could be frustrating to a user if they get stuck in this window. 

![AzureADB2CLogin](https://user-images.githubusercontent.com/6107674/61808324-063e1900-adf0-11e9-8978-72dfb544f44c.png)

**Comment by PeterStaev** [comment]
Hey @dehlers1000 , from what I know this dialog is presented by native Azure libraries since the plugin itself does not have any custom dialog. So sadly there is not much I can do.

**Comment by dehlers1000** [comment]
Thanks Peter. I appreciate the feedback.
