### ISSUE TITLE
Support Push Notifications

### ISSUE THREAD

**Issue by georgeedwards** [PeterStaev/nativescript-azure-mobile-apps#7]
Hi Peter,

I believe that the only feature not currently supported is Push Notifications? It would be great to add this. Again, I am more than happy to help with this (although I am not sure how helpful I was on the Auth PR). Anyway, it would be good to hear your thoughts.

**Comment by PeterStaev** [comment]
Hey @georgeedwards , notifications are part of another azure SDK/framework (similar to blob storage). So those should be made as separate plugins.

**Comment by Habeeb-mohamed** [comment]
It will be great to have push notification

**Comment by PeterStaev** [comment]
This is now implemented with the version 1.0 on npm.

**Comment by Habeeb-mohamed** [comment]
It is working fine in iOS, but have issues in android

**Comment by PeterStaev** [comment]
@Habeeb-mohamed , please open a new issue and provide more details what & where it is not working. I have tested on a geny simulator and it is working in my case, so it must be something specific to your setup.

**Comment by Habeeb-mohamed** [comment]
I am try to reproduce the issue in blank application. I will share the repository when done. Thank for quick response .

**Comment by Habeeb-mohamed** [comment]
I managed to fix the issue. If i follow steps found in azure portal. It has issue since google migrated to firebase. I have created the project in firebase and it is working fine.
